### ISSUE TITLE
APK download

### ISSUE THREAD

**Issue by IzzySoft** [CampbellMG/MiniMoods#1]
Nice to see a tracking-free FOSS app! Will there be a way to download the APK if one has no access to Play Store? One way would be to [tag your releases](https://github.com/CampbellMG/MiniMoods/releases) and attach the APK to the tag.

One more question: What for does the app need the Internet permission if it is just tracking the user's mood?

**Comment by CampbellMG** [comment]
Thanks for bringing this to my attention.

I've tagged the current release with an APK and will be sure to do so for any future releases. 

MiniMoods requests internet permissions for crash management.

**Comment by IzzySoft** [comment]
Thanks a lot! Yes, I see the app is using Sentry.io. I didn't check it out yet, but I guess you made that opt-in (so reporting is done with the users' consent). If I guessed right, your app should qualify for listing at [F-Droid](https://f-droid.org/) – the place where the free/libre open-source Android apps live. If you like, I can help you getting it there. Until then: with the next sync in about 11h from now, your app will become available [in my repo here](https://apt.izzysoft.de/fdroid/index/apk/com.cmgcode.minimoods). If that suits you, you can add [this badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to your Readme to link there, next go the Play Store badge :smiley:

Thanks again, and all the best for your project!

**Comment by IzzySoft** [comment]
@CampbellMG can you confirm Sentry is configured opt-in (i.e. the user is consulted **BEFORE** sending any data)? Because then I could remove the `Tracking` AntiFeature from [your app's listing](https://apt.izzysoft.de/fdroid/index/apk/com.cmgcode.minimoods).
