### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by GEkuL** [CampbellMG/MiniMoods#5]
Hi there,

I've not seen any updates on the app. Is the project alive or are there any other plans for active development?

**Comment by CampbellMG** [comment]
Hi mate,

The project is definitely still active with plans for the future, I'm just having a hard time finding time to work on them at the moment.

You can have a look through the open issues but I'm looking at support for multiple records per day, notifications and improved exports.

I'm definitely open to any PRs if you'd like to work on anything yourself.

**Comment by IzzySoft** [comment]
@CampbellMG I see 2 newer releases at PlayStore, but no corresponding releases/APKs here. Did you just forget them? To keep the app up-to-date at the [IzzyOnDroid repo](https://apt.izzysoft.de/fdroid), we'd need those APKs at their corresponding releases (see #1 for reference).
